# Generated by Django 3.0.8 on 2020-08-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_datetime', models.DateTimeField()),
                ('delivery_datetime', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'created'), ('delivered', 'delivered'), ('processed', 'processed'), ('cancelled', 'cancelled')], max_length=9)),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='beautyboxes.ProductSets')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='beautyboxes.Recipient')),
            ],
        ),
    ]
